### PR TITLE
Add French version

### PR DESCRIPTION
**Pull request by joachimesque**
I also added some small accessibility improvements on the language nav.

### CODE REVIEW

**Comment by aral** [comment]
@joachimesque Would you mind looking at the French translation provided by the Framalang folks submitted by @goofy-mdn in #3 and update your pull request if you feel it’s necessary. Thank you both for your submissions.

**Comment by goofy-mdn** [comment]
Please note my fix was only about the French version which needed some adjustments. I am sorry I am awkward with proper github management. Thanks.

**Comment by aral** [comment]
@joachimesque and @goofy-mdn once you’re both happy with this PR, please let me know and I’ll merge it :)

**Comment by aral** [comment]
Actually, in the interests of timeliness, I’m going to merge this PR and close the other one and if there are any corrections/updates anyone wants to make to the French translation going forward, please feel free to open a new PR. Thanks again for your time and contributions, I highly appreciate it.

**Pull request merged**
